SLURM_CLUSTER_ACCOUNT_NAME=nlp
SLURM_CLUSTER_PARTITION_NAME=jag-hi
SLURM_CLUSTER_EXCLUDE_NODES=
# jagupard18,jagupard19,jagupard20,jagupard21,jagupard22,jagupard23,jagupard24,jagupard25,jagupard26,jagupard27,sphinx1,sphinx2