#!/bin/bash

nlprun -n train_asr_mms_sceb_dro_0.1_groupinit -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_040/train_asr_mms_sceb_dro_0.1_groupinit.txt --mail-user bartelds@stanford.edu -d a6000 -x jagupard36,jagupard35 -r 64G -c 4 'source ../../../tools/activate_python.sh; make train_asr_mms_sceb_dro_0.1_groupinit'
nlprun -n train_asr_mms_aleb_dro_0.1 -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_040/train_asr_mms_aleb_dro_0.1.txt --mail-user bartelds@stanford.edu -d a6000 -x jagupard36,jagupard35 -r 64G -c 4 'source ../../../tools/activate_python.sh; make train_asr_mms_aleb_dro_0.1'
nlprun -n train_asr_xlsr_sceb_dro_0.1_groupinit -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_040/train_asr_xlsr_sceb_dro_0.1_groupinit.txt --mail-user bartelds@stanford.edu -d a6000 -x jagupard36,jagupard35 -r 64G -c 4 'source ../../../tools/activate_python.sh; make train_asr_xlsr_sceb_dro_0.1_groupinit'
nlprun -n train_asr_xlsr_aleb_dro_0.1 -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_040/train_asr_xlsr_aleb_dro_0.1.txt --mail-user bartelds@stanford.edu -d a6000 -x jagupard36,jagupard35 -r 64G -c 4 'source ../../../tools/activate_python.sh; make train_asr_xlsr_aleb_dro_0.1'

nlprun -n train_asr_mms_sceb_dro_0.01_groupinit -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_040/train_asr_mms_sceb_dro_0.01_groupinit.txt --mail-user bartelds@stanford.edu -d a6000 -x jagupard36,jagupard35 -r 64G -c 4 'source ../../../tools/activate_python.sh; make train_asr_mms_sceb_dro_0.01_groupinit'
nlprun -n train_asr_mms_aleb_dro_0.01 -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_040/train_asr_mms_aleb_dro_0.01.txt --mail-user bartelds@stanford.edu -d a6000 -x jagupard36,jagupard35 -r 64G -c 4 'source ../../../tools/activate_python.sh; make train_asr_mms_aleb_dro_0.01'
nlprun -n train_asr_xlsr_sceb_dro_0.01_groupinit -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_040/train_asr_xlsr_sceb_dro_0.01_groupinit.txt --mail-user bartelds@stanford.edu -d a6000 -x jagupard36,jagupard35 -r 64G -c 4 'source ../../../tools/activate_python.sh; make train_asr_xlsr_sceb_dro_0.01_groupinit'
nlprun -n train_asr_xlsr_aleb_dro_0.01 -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_040/train_asr_xlsr_aleb_dro_0.01.txt --mail-user bartelds@stanford.edu -d a6000 -x jagupard36,jagupard35 -r 64G -c 4 'source ../../../tools/activate_python.sh; make train_asr_xlsr_aleb_dro_0.01'

nlprun -n train_asr_mms_sceb_dro_0.001_groupinit -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_040/train_asr_mms_sceb_dro_0.001_groupinit.txt --mail-user bartelds@stanford.edu -d a6000 -x jagupard36,jagupard35 -r 64G -c 4 'source ../../../tools/activate_python.sh; make train_asr_mms_sceb_dro_0.001_groupinit'
nlprun -n train_asr_mms_aleb_dro_0.001 -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_040/train_asr_mms_aleb_dro_0.001.txt --mail-user bartelds@stanford.edu -d a6000 -x jagupard36,jagupard35 -r 64G -c 4 'source ../../../tools/activate_python.sh; make train_asr_mms_aleb_dro_0.001'
nlprun -n train_asr_xlsr_sceb_dro_0.001_groupinit -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_040/train_asr_xlsr_sceb_dro_0.001_groupinit.txt --mail-user bartelds@stanford.edu -d a6000 -x jagupard36,jagupard35 -r 64G -c 4 'source ../../../tools/activate_python.sh; make train_asr_xlsr_sceb_dro_0.001_groupinit'
nlprun -n train_asr_xlsr_aleb_dro_0.001 -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_040/train_asr_xlsr_aleb_dro_0.001.txt --mail-user bartelds@stanford.edu -d a6000 -x jagupard36,jagupard35 -r 64G -c 4 'source ../../../tools/activate_python.sh; make train_asr_xlsr_aleb_dro_0.001'

nlprun -n train_asr_mms_sceb_dro_0.0001_groupinit -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_040/train_asr_mms_sceb_dro_0.0001_groupinit.txt --mail-user bartelds@stanford.edu -d a6000 -x jagupard36,jagupard35 -r 64G -c 4 'source ../../../tools/activate_python.sh; make train_asr_mms_sceb_dro_0.0001_groupinit'
nlprun -n train_asr_mms_aleb_dro_0.0001 -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_040/train_asr_mms_aleb_dro_0.0001.txt --mail-user bartelds@stanford.edu -d a6000 -x jagupard36,jagupard35 -r 64G -c 4 'source ../../../tools/activate_python.sh; make train_asr_mms_aleb_dro_0.0001'
# nlprun -n train_asr_xlsr_sceb_dro_0.0001_groupinit -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_040/train_asr_xlsr_sceb_dro_0.0001_groupinit.txt --mail-user bartelds@stanford.edu -d a6000 -x jagupard36,jagupard35 -r 64G -c 4 'source ../../../tools/activate_python.sh; make train_asr_xlsr_sceb_dro_0.0001_groupinit'
# nlprun -n train_asr_xlsr_aleb_dro_0.0001 -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_040/train_asr_xlsr_aleb_dro_0.0001.txt --mail-user bartelds@stanford.edu -d a6000 -x jagupard36,jagupard35 -r 64G -c 4 'source ../../../tools/activate_python.sh; make train_asr_xlsr_aleb_dro_0.0001'

# nlprun -n train_asr_mms_sceb_dro_0.00001_groupinit -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_040/train_asr_mms_sceb_dro_0.00001_groupinit.txt --mail-user bartelds@stanford.edu -d a6000 -x jagupard36,jagupard35 -r 64G -c 4 'source ../../../tools/activate_python.sh; make train_asr_mms_sceb_dro_0.00001_groupinit'
# nlprun -n train_asr_mms_aleb_dro_0.00001 -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_040/train_asr_mms_aleb_dro_0.00001.txt --mail-user bartelds@stanford.edu -d a6000 -x jagupard36,jagupard35 -r 64G -c 4 'source ../../../tools/activate_python.sh; make train_asr_mms_aleb_dro_0.00001'
# nlprun -n train_asr_xlsr_sceb_dro_0.00001_groupinit -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_040/train_asr_xlsr_sceb_dro_0.00001_groupinit.txt --mail-user bartelds@stanford.edu -d a6000 -x jagupard36,jagupard35 -r 64G -c 4 'source ../../../tools/activate_python.sh; make train_asr_xlsr_sceb_dro_0.00001_groupinit'
# nlprun -n train_asr_xlsr_aleb_dro_0.00001 -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_040/train_asr_xlsr_aleb_dro_0.00001.txt --mail-user bartelds@stanford.edu -d a6000 -x jagupard36,jagupard35 -r 64G -c 4 'source ../../../tools/activate_python.sh; make train_asr_xlsr_aleb_dro_0.00001'
