#!/bin/bash

nlprun -n train-mms-ctc-aleb-0.0005 -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_011/train-mms-ctc-aleb-0.0005.txt --mail-user bartelds@stanford.edu -d a6000 -p high 'source ../../../tools/activate_python.sh; make train-mms-ctc-aleb-0.0005'
nlprun -n train-xlsr-ctc-aleb-0.0005 -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_011/train-xlsr-ctc-aleb-0.0005.txt --mail-user bartelds@stanford.edu -d a6000 -p high 'source ../../../tools/activate_python.sh; make train-xlsr-ctc-aleb-0.0005'
nlprun -n train-mms-ctc-sceb-0.0005 -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_011/train-mms-ctc-sceb-0.0005.txt --mail-user bartelds@stanford.edu -d a6000 -p high 'source ../../../tools/activate_python.sh; make train-mms-ctc-sceb-0.0005'
nlprun -n train-mms-ctc-aleb-0.0001 -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_011/train-mms-ctc-aleb-0.0001.txt --mail-user bartelds@stanford.edu -d a6000 -p high 'source ../../../tools/activate_python.sh; make train-mms-ctc-aleb-0.0001'
nlprun -n train-mms-ctc-sceb-0.0001 -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_011/train-mms-ctc-sceb-0.0001.txt --mail-user bartelds@stanford.edu -d a6000 'source ../../../tools/activate_python.sh; make train-mms-ctc-sceb-0.0001'
nlprun -n train-mms-ctc-aleb-5e-05 -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_011/train-mms-ctc-aleb-5e-05.txt --mail-user bartelds@stanford.edu -d a6000 'source ../../../tools/activate_python.sh; make train-mms-ctc-aleb-5e-05'
nlprun -n train-mms-ctc-sceb-5e-05 -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_011/train-mms-ctc-sceb-5e-05.txt --mail-user bartelds@stanford.edu -d a6000 'source ../../../tools/activate_python.sh; make train-mms-ctc-sceb-5e-05'
nlprun -n train-mms-ctc-aleb-1e-05 -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_011/train-mms-ctc-aleb-1e-05.txt --mail-user bartelds@stanford.edu -d a6000 'source ../../../tools/activate_python.sh; make train-mms-ctc-aleb-1e-05'
nlprun -n train-mms-ctc-sceb-1e-05 -g 1 -a /nlp/scr/bartelds/miniconda3/envs/asr-dro -o results/exp_011/train-mms-ctc-sceb-1e-05.txt --mail-user bartelds@stanford.edu -d a6000 'source ../../../tools/activate_python.sh; make train-mms-ctc-sceb-1e-05'
