encoder: transformer
encoder_conf:
    output_size: 256
    attention_heads: 8
    linear_units: 1024
    num_blocks: 2
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d2
    normalize_before: true

decoder: none

unused_parameters: true

model_conf:
    ctc_weight: 1.0

ctc_conf:
    accumulation: true
    agg: sum
    ctc_type: droctc
    dro_group_count: 6
    dro_q_epsilon: 1.0e-10
    dro_step_size: 0.0001
    smoothing: 0.1
    normalize_grad: true

frontend: s3prl
frontend_conf:
    download_dir: ./hub
    frontend_conf:
        path_or_url: facebook/wav2vec2-xls-r-300m
        upstream: hf_wav2vec2_custom
    multilayer_feature: true

preencoder: linear
preencoder_conf:
    input_size: 1024  # Note: If the upstream is changed, please change this value accordingly.
    output_size: 80

num_workers: 4
batch_type: sorted
batch_size: 4
accum_grad: 16
patience: none
init: xavier_uniform
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 2

optim: adam
optim_conf:
    lr: 0.0001
    weight_decay: 0.000001

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 10

num_iters_per_epoch: 1200
max_epoch: 40
