normalize: null

encoder: whisper
encoder_conf:
    whisper_model: medium
    dropout_rate: 0.0
    use_specaug: true
    specaug_conf:
        apply_time_warp: true
        time_warp_window: 5
        time_warp_mode: bicubic
        apply_freq_mask: true
        freq_mask_width_range:
        - 0
        - 40
        num_freq_mask: 2
        apply_time_mask: true
        time_mask_width_ratio_range:
        - 0.
        - 0.12
        num_time_mask: 5

decoder: whisper
decoder_conf:
    whisper_model: medium
    dropout_rate: 0.0

model_conf:
    ctc_weight: 0.0
    lsm_weight: 0.1
    length_normalized_loss: false
    sym_sos: "<|startoftranscript|>"
    sym_eos: "<|endoftext|>"
    # do_pad_trim: true         # should be set when doing zero-shot inference

frontend: null
input_size: 1                   # to prevent build_model() from complaining

num_workers: 0
batch_type: sorted
batch_size: 4
accum_grad: 8
patience: 5
max_epoch: 100
init: null
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 5

optim: adam
optim_conf:
    lr: 0.0001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

preprocessor: default
preprocessor_conf:
    whisper_task: "transcribe"

use_amp: true
num_att_plot: 0